# Generated by Django 4.1.5 on 2024-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=50)),
                ('fa_name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'layers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(help_text='منحصر به فرد', max_length=100, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='آدرس الکترونیکی')),
            ],
            options={
                'db_table': 'siteuser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkt', models.CharField(max_length=1000)),
                ('geojson', models.CharField(max_length=1000)),
                ('user_d', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uservectors',
                'managed': True,
            },
        ),
    ]
