# Generated by Django 4.1.5 on 2024-06-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservector',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservector',
            name='owner',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
